login: &login
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: 123456

#login: &login
#  adapter: postgresql
#  host: ec2-54-83-196-217.compute-1.amazonaws.com
#  port: 5432
#  username: xyfgqpgworqgnb
#  password: sV_gaczyeCrpCxrvBsy0aR7vGi

connection: &connection
  encoding: unicode
  pool: 5


development:
  database: publify_dev
  <<: *login
  <<: *connection

test:
  database: publify_tests
  <<: *login
  <<: *connection

production:
  database: publify
  <<: *login
  <<: *connection
